### ISSUE TITLE
raise Exception('Exceeded {} attempts'.format(interrupt))

### ISSUE THREAD

**Issue by MengHao666** [hassony2/obman#4]
Hello Yana,

First of all thank you for the great work!

I try to understand your codes about obman these days.And when i run " python shapenet_samplepoints.py", I got the warning message as follows:
   **Traceback (most recent call last):
  File "shapenet_samplepoints.py", line 50, in create_ray_samples
    points = sample_mesh(mesh, min_hits=min_hits)
  File "/home/haomeng/PycharmProjects/3DHand/obman/obman/samplemesh.py", line 80, in sample_mesh
    raise Exception('Exceeded {} attempts'.format(interrupt))
Exception: Exceeded 10 attempts**

It looks like the code just go through despite of such message. Does it matters?What does it mean actually?

**Comment by hassony2** [comment]
@MengHao666 ,

Sorry for the very late reply. For future reference, this is likely linked to #7
